### ISSUE TITLE
Button effects for links are missing

### ISSUE THREAD

**Issue by graue70** [ad-freiburg/aqqu-frontend#2]
The link to 'Detailed Aqqu' in the bottom right corner is not a button. This means that the following usual functionality is missing:
1. Middle click to open in a new tab
2. Right click for more options
3. Hover to see the URL it links to in the bottom of the browser
4. Visual hover effect (to even notice that it is possible to click)

This is also true for the 'ASK' link, but 1-3 are usual search engine behavior and should probably be left this way. However, a visual hover effect should be introduced for this one, too.

**Comment by flackbash** [comment]
I agree with the visual hover effect and implemented it.

The problem with the "Detailed Aqqu" element is not that it's not a button, but rather that it's not an anchor element.
I used this implementation, since the form containing the button (or input of type "submit" - does not really matter which one is chosen) allows me to append the current question as parameter to the url without any fuss. This in turn inserts the current question into the input field on the "Detailed Aqqu" page which is an essential behavior that was requested at the highest level ;)
I think this is a very clean way of achieving this behavior. Do you have a clean alternative using an anchor?
Apart from that I think 1-3 are nice-to-have's but not essential, considering that this is a website whose main purpose is to demonstrate our chair's prototypes and not to be used by hundred's of people.

**Comment by hannahbast** [comment]
@flackbash Isn't it easy to associate an abritrary style and an arbitray behaviour with any HTML element (including an anchor element) via the right entries in the CSS and by associating a click event with it in the JavaScript code? Or am I missing something here?

**Comment by flackbash** [comment]
It may not be difficult, but at least for me it was time consuming because there several things to consider.

Implementing onclick to append the url is of course not enough since middle and right click need to be handled as well, implementing onmouseup is not enough, since gestures (e.g. using [Gesturefy](https://addons.mozilla.org/de/firefox/addon/gesturefy/)) are not working as expected and implementing onmouseenter or onmouseover is not a completely clean solution either, since the url preview is created before the function code is executed such that after changing the question, the url preview will be wrong on the first mouseover (does someone now how to prevent that?).
And then of course using tab + enter to click the button needed to be handled separately.
I'm still not sure if I handled all possible cases. So there is more functionality now, but in my opinion it was more consistent before and it was very straight forward what was happening. That's what I meant with "clean" in my previous comment.

Do you both prefer the new version? It's running on [http://nkaba.informatik.privat:8183/](http://nkaba.informatik.privat:8183/). The previous version is running on  [http://aqqu.cs.uni-freiburg.de/](http://aqqu.cs.uni-freiburg.de/)

**Comment by flackbash** [comment]
79060f6086f fixes the problems described in the previous comment. The newest version is running on [ http://aqqu.cs.uni-freiburg.de/]( http://aqqu.cs.uni-freiburg.de/)
