### ISSUE TITLE
Long load times for autocompletion

### ISSUE THREAD

**Issue by graue70** [ad-freiburg/aqqu-frontend#6]
This issue might fit better to https://github.com/ad-freiburg/qac. I'm not sure.

If I input 'what is the capital of ' and then quickly type 'japa', the autocompletion takes a considerable amount of time to follow the input. At the beginning, it suggests 'Kampala', after a while it suggests 'Jakarta' before it finally suggests 'Japan'.
The requests sent to qac apparently take close to 2 seconds:
![aqqu_qac_long_load_time](https://user-images.githubusercontent.com/23035329/76535524-518a6200-647b-11ea-96a6-ac677a17b3f2.png)

This makes using the completions a little funky. When you press Enter you can't always be sure which suggestion is actually selected.

**Comment by flackbash** [comment]
Yes, this is caused by the QAC API and is not the website's fault ;)
I will have a look into it. However, I assume this is a general performance thing that doesn't have a quick fix and comes from computing language model probabilities, word2vec similarity and co-occurrence counts between tons of entities and words... So there will probably not be any improvement on this any time soon.
