### ISSUE TITLE
Autocomplete requests are sent even though input wasn't changed

### ISSUE THREAD

**Issue by graue70** [ad-freiburg/aqqu-frontend#7]
There some situations where requests are send to qac, even though the input hasn't changed. This happens when there is an incomplete query in the aqqu text box. Two examples:

1. Switching the tab twice with Ctrl + Tab (on Firefox).
1. Pressing the windows key twice (opening the OS menu and closing it again).
1. Opening the screenshot tool (on Ubuntu), taking a screenshot (request is sent to qac), choosing a file name for the screenshot, confirm the selection (another request is sent).

This can be noticed by having open the developer console on the network tab and doing the mentioned actions.

**Comment by flackbash** [comment]
If the input field is focused, then for every key up event a request is sent to the QAC API save a few exceptions that are necessary for the website to function properly (up/down arrow, ctrl, enter).
I added some common key events (tab, left/right arrow, alt, home) to the list of exceptions.

Also, a request was sent when the input field gained focus. I removed this behavior, since I think it was not necessary in the current version of the website.

In general though, these requests should not be a problem, since the results in these cases are cached anyway.
